# Generated by Django 2.1.7 on 2019-03-30 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('hourly_rate', models.IntegerField(default=0)),
                ('max_hour_perday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('hourly_rent', models.IntegerField(default=0)),
                ('max_hour_perday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=50)),
                ('contractor_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 3, 29, 20, 44, 56, 157741))),
                ('status', models.CharField(choices=[(0, 'open'), (1, 'review'), (2, 'Finallized')], default='', max_length=10)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timecard_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('code_type', models.CharField(choices=[('J', 'job_code'), ('M', 'machine_code')], default='', max_length=10)),
                ('hours', models.IntegerField(default=0)),
                ('sitecode_id', models.ForeignKey(on_delete='casscade', to='timecard.Timecard')),
            ],
        ),
    ]
