# Generated by Django 2.1.7 on 2019-04-02 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('hourly_rate', models.IntegerField(default=0)),
                ('max_hour_perday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('site_code', models.CharField(max_length=50)),
                ('job_code', models.ForeignKey(on_delete='casscade', to='timecard.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('hourly_rent', models.IntegerField(default=0)),
                ('max_hour_perday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('site_code', models.CharField(max_length=50)),
                ('machine_code', models.ForeignKey(on_delete='casscade', to='timecard.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(max_length=50)),
                ('contractor_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 4, 2, 11, 16, 14, 824374))),
                ('status', models.CharField(choices=[('open', 'open'), ('review', 'review'), ('Finallized', 'Finallized')], default='open', max_length=10)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
