# Generated by Django 2.1.7 on 2019-04-02 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineentry',
            old_name='hours_useded',
            new_name='hours_used',
        ),
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 7, 1, 20, 22093)),
        ),
    ]
