# Generated by Django 2.1.7 on 2019-03-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 12, 25, 38, 712766)),
        ),
    ]
