# Generated by Django 2.1.7 on 2019-04-02 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 14, 22, 1, 609292)),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('review', 'review'), ('finalized', 'finalized')], default='', max_length=10),
        ),
    ]
