# Generated by Django 2.1.7 on 2019-04-02 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_auto_20190402_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 14, 22, 6, 471523)),
        ),
    ]
