# Generated by Django 2.1.7 on 2019-03-30 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_auto_20190330_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 18, 47, 42, 844911)),
        ),
    ]
