# Generated by Django 2.1.7 on 2019-04-01 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0003_auto_20190330_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 17, 29, 34, 64479)),
        ),
    ]
