# Generated by Django 2.1.7 on 2019-04-01 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0004_auto_20190401_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 19, 16, 30, 597591)),
        ),
    ]
